spring.datasource.url=jdbc:mysql://root:uNTFlGqhDDbzIluaLQGFhdwIQMBXNuUr@viaduct.proxy.rlwy.net:13631/railway
spring.datasource.username=root
spring.datasource.password=uNTFlGqhDDbzIluaLQGFhdwIQMBXNuUr
url=https://purna.up.railway.app