spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
url=https://jansheva.up.railway.app

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
