spring.datasource.url=jdbc:mysql://localhost:3306/hospitalmanagementhn?createDatabaseIfNotExist=true
spring.datasource.username=root
<<<<<<< HEAD
<<<<<<< Updated upstream
spring.datasource.password=gEUZaXqcAtkHDCztZllrPKRlZnGvQvpZ
=======
spring.datasource.password=gEUZaXqcAtkHDCztZllrPKRlZnGvQvpZ
>>>>>>> Stashed changes
=======
spring.datasource.password=Intakhab
url=http://localhost:8080
>>>>>>> ba017d5d2411a9817a09c3ae2ef9dabf1aa60300
